version: "3"

services:
  http:
    build:
      dockerfile: docker/Dockerfile
      target: http
    image: meysam81/todors:local
    entrypoint: todors
    command: serve http -H 0.0.0.0 -p 8080
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
      - DB_URL=/data/db.sqlite
    volumes:
      - todors:/data
    depends_on:
      - migration
    restart: unless-stopped

  grpc:
    build:
      dockerfile: docker/Dockerfile
      target: http
    image: meysam81/todors:local
    entrypoint: todors
    command: serve grpc -H 0.0.0.0 -p 50051
    ports:
      - "50051:50051"
    environment:
      - LOG_LEVEL=debug
      - DB_URL=/data/db.sqlite
    volumes:
      - todors:/data
    depends_on:
      - migration
    restart: unless-stopped

  supervisor:
    build:
      dockerfile: docker/Dockerfile
      target: supervisor
    image: meysam81/todors:local
    ports:
      - "8081:8080"
      - "50052:50051"
    environment:
      - LOG_LEVEL=debug
      - DB_URL=/data/db.sqlite
    volumes:
      - todors:/data
    depends_on:
      - migration
    restart: unless-stopped

  migration:
    build:
      dockerfile: docker/Dockerfile
    image: meysam81/todors:local
    entrypoint: todors
    command: list
    environment:
      - LOG_LEVEL=debug
      - DB_URL=/data/db.sqlite
    volumes:
      - todors:/data
    restart: on-failure

volumes:
  todors:
