name: automated-tests
concurrency:
  group: automated-tests-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable
        run: |
          rustup toolchain install stable
      - name: Install mold
        uses: rui314/setup-mold@v1
      - name: Run tests
        run: |
          cargo test --all-features --all-targets --all | tee -a $GITHUB_STEP_SUMMARY
