name: publish-crate

concurrency:
  group: publish-crate-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable
        run: |
          rustup toolchain install stable
      - name: Install mold
        uses: rui314/setup-mold@v1
      - name: Install protoc
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: Publish
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
