name: trivy-scan

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          format: table
          scan-type: "fs"
